# base:
#   db_prefix:
#   db_user:
#   db_hostname:
#   db_port:
#   # if this is not false it will directly take pass from this variable, else it will take from db_pass_secretref
#   db_pass_direct:
#   es_url:
#   kibana_url:

debezium_connectors:
  enabled: true
  delay_between_connectors: "20s"
  # existingConfigMap:
  dbs:
  - name: "mosip_master"
    tables: "master.doc_type,master.registration_center"
  - name: "mosip_audit"
    tables: "audit.app_audit_log"
  - name: "mosip_prereg"
    tables: "prereg.applicant_demographic,prereg.applicant_demographic_consumed,prereg.applicant_document,prereg.applicant_document_consumed,prereg.reg_appointment,prereg.reg_appointment_consumed,prereg.reg_available_slot,prereg.otp_transaction"
  - name: "mosip_ida"
    tables: "ida.auth_transaction"
  - name: "mosip_regprc"
    tables: "regprc.registration,regprc.registration_list,regprc.anonymous_profile"
  - name: "mosip_idrepo"
    tables: "idrepo.anonymous_profile,idrepo.channel_info"
  - name: "postgres"
    tables: "public.packet_tracker"

es_kafka_connectors:
  enabled: true
  delay_between_connectors: "10s"
  # existingConfigMap:
